services:
  workshops:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - workshops
